### ISSUE TITLE
Incorrect use of config('nova.url')

### ISSUE THREAD

**Issue by ns139426** [jackabox/nova-duplicate-field#10]
From config/nova.php
```
/*
    |--------------------------------------------------------------------------
    | Nova App URL
    |--------------------------------------------------------------------------
    |
    | This URL is where users will be directed when clicking the application
    | name in the Nova navigation bar. You are free to change this URL to
    | any location you wish depending on the needs of your application.
    |
    */
```
Nova uses 'nova.path' throughout, it would seem logical for this code to do the same.

**Comment by jackabox** [comment]
The code uses both to provide an absolute URL to the API endpoint.

`config('nova.url') . config('nova.path')`

**Comment by ns139426** [comment]
I appreciate the intention of the code, it's simply not a reliable solution given the nature of the nova.path value.

It's not uncommon for nova.url to be a complete URL to the Nova dashboard. In this instance, appending nova.path leads to an incorrect URL. I might be missing something but if Nova uses relative paths throughout, surely this package could do the same?

**Comment by jackabox** [comment]
Spotted, yes this should reference just the nova.path. Thanks for pointing this out, will patch soon.

**Comment by jackabox** [comment]
Closed in latest commit.
