### ISSUE TITLE
window.location.replace

### ISSUE THREAD

**Issue by kikoseijo** [jackabox/nova-duplicate-field#11]
After duplication it tries to redirect, using:

```js
window.location.replace(response.data.destination);
```

But this seems to remove the url and takes me to a not found, not sure it could be due to being working in valet, but should not be the case.

for me replaces full url into:

```
http://admin/resources/tasks/50
```

as you see, will remove the url, `window.location(response.data.destination)` should do the trick.

Am I right? -last commit did break this.

**Comment by jackabox** [comment]
Yes you are right. Thanks for spotting this. Will look at patching it tomorrow.

**Comment by jackabox** [comment]
Just published v0.2.6 which should request the HTTP Host and redirect as needed. Can you confirm if this fixes for you? @kikoseijo

**Comment by kikoseijo** [comment]
Nope  :(

Now will try to take me to `http://climtel.test/admin/resources/://climtel.test//admin/resources/tasks/51`

Trying on a local valet server.

**Comment by jackabox** [comment]
Apologies, I've not had enough tea and missed out the protocol. The latest tagged release should address this.

**Comment by holubar** [comment]
Working locally on Valet, when successfuly duplicated resource, I get on 404 page in Nova. Nova v3.2.1
![image](https://user-images.githubusercontent.com/34790487/79110920-c94df400-7d7b-11ea-8056-51c0ea1bceec.png)
