### ISSUE TITLE
Would be nice to have a callback

### ISSUE THREAD

**Issue by nilsE** [jackabox/nova-duplicate-field#17]
Since i have to change some data (for example a quotation number or to add "copy" to the title), it would be nice to have a callback which is executed before saving the new record

**Comment by nilsE** [comment]
can be done with an observer :-)

`    public function replicating (Model $model) {

        $model->title = $model->title . ' - copied';
     }
`

**Comment by jackabox** [comment]
@nilsE glad you got this sorted, going to add an example of this into the docs as I believe it keeps getting missed.
