### ISSUE TITLE
Updated your controller to support nearly all relations

### ISSUE THREAD

**Issue by vahidRP** [jackabox/nova-duplicate-field#18]
Hi,
i changed your DuplicateController.php  to support nearly all relations. I will upload the file here and please overwrite it with the existing one in the github repository.
TNX

**Comment by jackabox** [comment]
Hi, If you want to open this as a pull request with the necessary changes. I'll have a review.

**Comment by vahidRP** [comment]
well......
I'd like to, But i have no idea how to do that.

**Comment by jackabox** [comment]
@vahidRP if you click the "Fork" button in the top right next to the star and watch. You'll get a "copy" of the repository in your Github. You can then clone this locally using either an IDE or `git clone` command. If you make the changes on this version, then come back the repository and click "Pull Requests" and create a new one this will show the changes you've made to which files. :)

**Comment by vahidRP** [comment]
Thank you very much. I'll do it right now.
