### ISSUE TITLE
Incorporate base behavior to pass $except array of values not to replicate

### ISSUE THREAD

**Issue by ckonkel** [jackabox/nova-duplicate-field#19]
Might help some people avoid using the replicating event for scenarios like unique values.
https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Model.html#method_replicate

**Comment by glennjacobs** [comment]
See my pull request here #23

**Comment by jackabox** [comment]
@glennjacobs Merged into v0.3.0, closing this for now! Thanks.
