### ISSUE TITLE
Duplicate model with unique fields

### ISSUE THREAD

**Issue by masterix21** [jackabox/nova-duplicate-field#4]
Hi,

how i can duplicate a model with fields unique? A great solution could be a button "duplicate" in edit mode.

Any idea?

**Comment by jackabox** [comment]
Hey,

There isn't a way to duplicate on unique data at the minute as this would not be able to be inserted automatically. I'd have to think of a solution for this - happy to open a PR if you wish.

A button in the view mode would be fine.

**Comment by cord** [comment]
a button "save new" / "save as copy" would work as well

**Comment by morphsteve** [comment]
@masterix21 You can hook into the replicating model event, e.g.

```php
class Post extends Model
{
    protected static function boot()
    {
         parent::boot();

         static::replicating(function ($post) {
             $post->title = "Copy of {$post->title}";
             $post->slug = '...';
        });
    }
}

**Comment by jackabox** [comment]
@morphsteve Apologies for missing this. Definitely worth updating the readme.md as most tweaks people want to suggest can be done through Observers, so might be worth an update. Feel free to open a PR, or I'll try to get it in ASAP.

**Comment by ns139426** [comment]
Another option for setting the unique fields manually could be to wrap this into an Action and use the ActionFields to set validated values. I used this today https://gist.github.com/ns139426/aa4997886cef5b5c9e11de6e0fdffb5a

I don't want to hijack this package as I've used it for a few months quite happily but my requirements changed a little and Actions definitely add some pre-built niceties.
