### ISSUE TITLE
405 Method not Allowed

### ISSUE THREAD

**Issue by audetcameron** [jackabox/nova-duplicate-field#5]
Route /nova-duplicate   405 Method not allowed.
from the browser console.
```
duplicate-field:680
GET http://itr.test/nova-duplicate 405 (Method Not Allowed)
dispatchXhrRequest @ duplicate-field:680
xhrAdapter @ duplicate-field:514
dispatchRequest @ duplicate-field:1851
Promise.then (async)
request @ duplicate-field:1117
Axios.(anonymous function) @ duplicate-field:1137
wrap @ duplicate-field:493
onClick @ duplicate-field:949
click @ duplicate-field:2065
e @ vendor.js?id=9acde073472c5725344b:1
Yr.e._withTask.o._withTask @ vendor.js?id=9acde073472c5725344b:1
```

Error: Request failed with status code 405
    at createError (duplicate-field:705)
    at settle (duplicate-field:1379)
    at XMLHttpRequest.handleLoad (duplicate-field:579)

**Comment by jackabox** [comment]
Hey,

Are you passing relations through on this? Wondering if it's a conflict there that is causing problems. Just installed this on a new project and seems to be working fine. 

Just pushed an update with a couple of fallbacks in hoping that it catches for where the parameter doesn't exist.

**Comment by audetcameron** [comment]
No Relationships, 
 `
            DuplicateField::make('Duplicate')
            ->withMeta([
                'resource' => 'Page', // resource url
                'model' => 'App\Models\Page', // model path
                'id' => $this->id, // id of record
                'relations' => [] // an array of any relations to load (nullable).
            ]),
`

The icon shows up but I get the console error of 405.  Which typically relates to token / cors issue I believe.
It is looking for mydomain.com/nova-duplicate    is it supposed to be looking for mydomain.com/api/nova-duplicate  ?

thanks again.

**Comment by jackabox** [comment]
@audetcameron 

Can you paste your config for nova? `config/nova.php`. Wondering if that's what could be causing the issue. I may have hard coded part of the site that shouldn't have been.

**Comment by audetcameron** [comment]
Sure Thing:
`
<?php

use Laravel\Nova\Http\Middleware\Authorize;
use Laravel\Nova\Http\Middleware\BootTools;
use Laravel\Nova\Http\Middleware\Authenticate;
use Laravel\Nova\Http\Middleware\DispatchServingNovaEvent;

return [

    /*
    |--------------------------------------------------------------------------
    | Nova App Name
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to display the name of the application within the UI
    | or in other locations. Of course, you're free to change the value.
    |
    */

    'name' => 'Nova Site',

    /*
    |--------------------------------------------------------------------------
    | Nova App URL
    |--------------------------------------------------------------------------
    |
    | This URL is where users will be directed when clicking the application
    | name in the Nova navigation bar. You are free to change this URL to
    | any location you wish depending on the needs of your application.
    |
    */

    'url' => env('APP_URL', '/'),

    /*
    |--------------------------------------------------------------------------
    | Nova Path
    |--------------------------------------------------------------------------
    |
    | This is the URI path where Nova will be accessible from. Feel free to
    | change this path to anything you like. Note that this URI will not
    | affect Nova's internal API routes which aren't exposed to users.
    |
    */

    'path' => '/admin',

    /*
    |--------------------------------------------------------------------------
    | Nova Route Middleware
    |--------------------------------------------------------------------------
    |
    | These middleware will be assigned to every Nova route, giving you the
    | chance to add your own middleware to this stack or override any of
    | the existing middleware. Or, you can just stick with this stack.
    |
    */

    'middleware' => [
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],

    'tinymce_api_key' => env('TINYMCE_API_KEY'),


];

`

**Comment by jackabox** [comment]
Seems fine,  what about `php artisan route:list` can you see the route registered it's trying to post to?

```
|        | POST     | nova-duplicate                                                                             |                       | Jackabox\DuplicateField\Http\Controllers\DuplicateController@duplicate     | web
```

**Comment by audetcameron** [comment]
It's there: 
`
|        | POST                                   | nova-duplicate                                                                             |                                        | Jackabox\DuplicateField\Http\Controllers\DuplicateController@duplicate     | web  
`

thanks for your time in troubleshooting. :)

**Comment by audetcameron** [comment]
If it helps:  I tracked it down to this request causing the 405  :   un minified duplicate-field.js  line 680
`
    // Send the request
    request.send(requestData);
  });
`

**Comment by jackabox** [comment]
Hey, think I've got this and the url is posting incorrectly, give me a few mins to just debug.

**Comment by jackabox** [comment]
@audetcameron Just published a new version, can you double check if this fixes anything please.

**Comment by audetcameron** [comment]
Sure thing, be back in a bit with an update

**Comment by jackabox** [comment]
@audetcameron Can't replicate this at the minute so I'm going to need to take some time to debug. My apologies.

**Comment by audetcameron** [comment]
> @audetcameron Can't replicate this at the minute so I'm going to need to take some time to debug. My apologies.

no need to apologize.  :)   Look forward to helping you get to the bottom of it.
